require:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/{rails,rake,bundle,setup,spring}'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

RSpec/MultipleExpectations:
  Max: 3
