default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  redis:
    # For a custom redis port or server, change the url string.
    url: <%= "redis://localhost:6379/1" %>

development:
  <<: *default

  # The database url connection string, the user is rails and the password is stored in the credentials file. The user probably does not exist yet, so you will need to create it.
  # To create additional roles in postgres see `$ createuser --help`.
  url: <%= "postgresql://rails:#{Rails.application.credentials.dig(:db_password)}@localhost/the_simple_api_development" %>

  # If you need to change the user or port, you can do so by changing the url string.
  # url: <%= "postgresql://your_user:#{Rails.application.credentials.dig(:db_password)}@localhost:your_port/the_simple_api_development" %>

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
    #   debug5, debug4, debug3, debug2, debug1,
    #   log, notice, warning, error, fatal, and panic
    # Defaults to warning.
    #min_messages: notice

  # Warning: The database defined as "test" will be erased and
  # re-generated from your development database when you run "rake".
  # Do not set this db to the same as development or production.
test:
  <<: *default
  url: <%= "postgresql://rails:#{Rails.application.credentials.dig(:db_password) || 'default_password'}@localhost/the_simple_api_test" %>


production:
  <<: *default
  url: <%= "postgresql://rails:#{Rails.application.credentials.dig(:db_password)}@localhost/the_simple_api_production" %>
