name: Deploy
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      RELEASE_VERSION: ${{ github.event.release.tag_name }}

    steps:
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: github-actions-deploy
          aws-region: ${{ vars.AWS_REGION }}
          output-credentials: true

      - name: Get SSM Parameters
        uses: dkershner6/aws-ssm-getparameters-action@v2
        with:
          parameterPairs: "/simple_app/bastion_sg_id = BASTION_SG_ID, /simple_app/bastion_host_ip = BASTION_HOST_IP, /simple_app/db_host = DB_HOST"

      - name: Get GitHub Actions IP
        run: echo "GITHUB_ACTION_IP=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_ENV

      - name: Allow GitHub Actions IP in Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $BASTION_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ env.GITHUB_ACTION_IP }}/32
          echo "SG_RULE_ADDED=true" >> $GITHUB_ENV

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}

      - name: SSH Key Scan for Bastion Host
        run: |
          ssh-keyscan -H $BASTION_HOST_IP >> ~/.ssh/known_hosts

      - name: Create SSH Config File
        run: |
          echo "Host bastion" > ~/.ssh/config
          echo "  HostName $BASTION_HOST_IP" >> ~/.ssh/config
          echo "  User ec2-user" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo "" >> ~/.ssh/config
          echo "Host simple-api-server" >> ~/.ssh/config
          echo "  HostName 10.0.4.219" >> ~/.ssh/config
          echo "  User ubuntu" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo "  ProxyJump bastion" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Checkout Code at Release Tag
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Deploy via Capistrano
        id: deploy
        run: bundle exec cap production deploy BRANCH=$RELEASE_VERSION DB_HOST=$DB_HOST
        continue-on-error: true

      - name: Revoke GitHub Actions IP from Security Group
        if: env.SG_RULE_ADDED == 'true'
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $BASTION_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ env.GITHUB_ACTION_IP }}/32

      - name: Fail Job if Deployment Fails
        if: steps.deploy.outcome == 'failure'
        run: exit 1
