name: CI
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Try build
        run: bin/rails runner "print 'ok'"
  tests:
    name: tests
    needs: build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: default_password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup test database and run test
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:setup
          bundle exec rspec

      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failedThreshold: 100
      - name: Upload Code Coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage/

  release:
    name: release
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Linter
        run: bundle exec rubocop
      - name: Security Checks
        run: |
          bundle exec brakeman -z
          gem install bundle-audit
          bundle-audit update
          bundle-audit
